#!/bin/bash

installPath="/usr/local/bin/xrdpwho"
targetPath="/opt/xrdp-who/xrdpwho"
permissionsValue="775"

case $1 in
	-xrdp)
		./xrdp-who.sh
		;;
	-xorg)
		./xrdp-who-xorg.sh
		;;
	-xvnc)
		./xrdp-who-xvnc.sh
		;;
	'--install')
		echo ""
		if [ -e "$installPath" ]; then
			echo "ERROR: file already exists at target install path \"$installPath\""
		else
			echo "Creating symlink at install path \"$installPath\" to target \"$targetPath\"..."
			sudo ln -s "$targetPath" "$installPath"

			echo "Setting permissions for \"$targetPath\"..."
			sudo chmod "$permissionsValue" "$targetPath"

			echo "Setting permissions for \"$installPath\"..."
			sudo chmod "$permissionsValue" "$installPath"
		fi
		if [ -L "$installPath" ]; then
			if [ $(readlink -f "$installPath") == "$targetPath" ]; then
				if [ $(stat -L -c "%a" "$installPath") == "$permissionsValue" ]; then
					if [ $(stat -L -c "%a" "$targetPath") == "$permissionsValue" ]; then
						echo "Install successful"
					else
						echo "ERROR: Failed to set permissions on target path \"$targetPath\""
					fi
				else
					echo "ERROR: Failed to set permissions on install path \"$installPath\""
				fi
			else
				echo "ERROR: Failed to create symlink at install path \"$installPath\" to target \"$targetPath\""
			fi
		else
			echo "ERROR: Failed to create symlink at install path \"$installPath\" to target \"$targetPath\""
		fi
		echo ""
		;;
	*)
		echo ""
		echo "Command Format: xrdpwho <arg>"
		echo ""
		echo "Arguments:"
		echo " -xorg : Show info on all current xorg sessions (recommended option for quick xrdp user status check)"
		echo " -xrdp : Show info on all current xrdp sessions"
		echo " -xvnc : Show info on all current xvnc sessions"
		echo ""
		;;
esac
